---
- name: Install epel-repo
  when: enable_epel
  import_role:
      name: geerlingguy.repo-epel
  tags: epel

- name: Install packages
  yum:
    name: "{{ item }}"
  become: yes
  when: ansible_os_family == 'RedHat'
  with_items:
    - "{{ system_packages }}"
